name: Generate snake 

on:
  schedule: [{cron: "0 6 * * 0,3,6"}]

  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  generate_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit and push snake.svg
        run: |
          git add dist/snake.svg
          git commit -m "Update snake.svg"
          git push origin main
